sudo: required

language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "8"

notifications:
  email:
    - mark.mathis@vertigomusic.com

script:
  - npm run lint
  - npm run build
  - npm test

deploy:
  provider: gae
  keyfile: "api_credentials.json"
  project: "mark-dev-project" 
  on: "master" 